<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mondo_api" nsURI="mondo_api" nsPrefix="">
  <eAnnotations source="doc">
    <details key="dServices" value="&#xA;The present section lists the services offered by the current version of the&#xA;MONDO platform. For each service, the available operations are presented, along&#xA;with the parameters they take, their return type and the exceptions they may&#xA;throw if they fail.&#xA;&#xA;In addition to their explicitly listed exceptions, operations requiring authentication&#xA;may throw an AuthenticationFailed exception if the user fails to provide valid credentials&#xA;or does not have the required permissions. In its current version, the MONDO platform&#xA;assumes that authenticated users will have the necessary permissions. The deliverable D6.3&#xA;in M24 will include a more fine-grained permissions system which separates authentication and&#xA;authorization.&#xA;"/>
  </eAnnotations>
  <eAnnotations source="thrift">
    <details key="javans" value="uk.ac.york.mondo.integration.api"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Users">
    <eAnnotations source="doc">
      <details key="d" value="The majority of service operations provided by the MONDO&#xA;&#x9;&#x9;platform require user authentication (indicated in the top-left&#xA;&#x9;&#x9;cell of each operation table) to prevent unaccountable use.&#xA;&#x9;&#x9;As such, the platform needs to provide basic user management service operations&#xA;&#x9;&#x9;for creating, updating and deleting user accounts."/>
    </eAnnotations>
    <eOperations name="createUser" eExceptions="#//UserExists">
      <eAnnotations source="doc">
        <details key="d" value="Creates a new platform user"/>
      </eAnnotations>
      <eParameters name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="A unique identifier for the user"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The desired password"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="profile" eType="#//UserProfile">
        <eAnnotations source="doc">
          <details key="d" value="The profile of the user"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="testCredentials" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="Tests whether the provided credentials are valid"/>
        <details key="auth" value="false"/>
      </eAnnotations>
      <eParameters name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="A user name"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The password for that user name"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="updateUser" eExceptions="#//UserNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Updates the profile of a platform user"/>
      </eAnnotations>
      <eParameters name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the user to update the profile of"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="profile" eType="#//UserProfile">
        <eAnnotations source="doc">
          <details key="d" value="The updated profile of the user"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="deleteUser" eExceptions="#//UserNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Deletes a platform user"/>
      </eAnnotations>
      <eParameters name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the user to delete"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hawk">
    <eAnnotations source="doc">
      <details key="d" value="&#xA;The following service operations expose the capabilities of the Hawk heterogeneous model indexing&#xA;framework developed in Work Package 5. The framework is discussed in detail in D5.2 and D5.3&#xA;"/>
    </eAnnotations>
    <eOperations name="createInstance">
      <eAnnotations source="doc">
        <details key="d" value="Creates a new Hawk instance (stopped)."/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The unique name of the new Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="adminPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The admin password for encrypting credentials"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listInstances" upperBound="-1" eType="#//HawkInstance">
      <eAnnotations source="doc">
        <details key="d" value="Lists the details of all Hawk instances"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="removeInstance" eExceptions="#//HawkInstanceNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Removes an existing Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance to remove"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="startInstance" eExceptions="#//HawkInstanceNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Starts a stopped Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance to start"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="adminPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The admin password for encrypting credentials"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="stopInstance" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Stops a running Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance to stop"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="registerMetamodels" eExceptions="#//HawkInstanceNotFound #//InvalidMetamodel #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Registers a set of file-based metamodels with a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="metamodel" upperBound="-1" eType="#//File">
        <eAnnotations source="doc">
          <details key="d" value="The metamodels to register.&#xA;&#x9;&#x9;&#x9;More than one metamodel files can be provided in one&#xA;&#x9;&#x9;&#x9;go to accomodate fragmented metamodels."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="unregisterMetamodel" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Unregisters a metamodel from a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="metamodel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the metamodel"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listMetamodels" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Lists the URIs of the registered metamodels of a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listQueryLanguages" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Lists the supported query languages and their status"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="query" upperBound="-1" eType="#//ScalarOrReference" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning #//UnknownQueryLanguage #//InvalidQuery">
      <eAnnotations source="doc">
        <details key="d" value="Runs a query on a Hawk instance and returns a collection of primitives and/or model elements (see ModelElement struct)"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The query to be executed"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the query language used (e.g. EOL, OCL)"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The scope of the query (e.g. *.uml)"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="resolveProxies" upperBound="-1" eType="#//ModelElement" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Returns populated model elements for the provided proxies"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="ids" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="Proxy model element IDs to be resolved"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeAttributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include attributes (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeReferences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include references (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="addRepository" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning #//UnknownRepositoryType #//VCSAuthenticationFailed">
      <eAnnotations source="doc">
        <details key="d" value="Asks a Hawk instance to start monitoring a repository"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the repository to monitor"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The type of repository to be monitored"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="A valid set of credentials that has read-access to the repository"/>
          <details key="optional" value="true"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="removeRepository" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Asks a Hawk instance to stop monitoring a repository"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the repository to stop monitoring"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listRepositories" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Lists the URIs of the repositories monitored by a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listRepositoryTypes" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Lists the available repository types in this installation"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="listFiles" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Lists the paths of the files of the indexed repository"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="repository" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the indexed repository"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="filePatterns" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="File name patterns to search for (* lists all files)"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="configurePolling" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning #//InvalidPollingConfiguration">
      <eAnnotations source="doc">
        <details key="d" value="Sets the base polling period and max interval of a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="doc">
          <details key="d" value="The base polling period (in seconds)"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="doc">
          <details key="d" value="The maximum polling interval (in seconds)"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="addDerivedAttribute" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning #//InvalidDerivedAttributeSpec">
      <eAnnotations source="doc">
        <details key="d" value="Add a new derived attribute to a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="spec" eType="#//DerivedAttributeSpec">
        <eAnnotations source="doc">
          <details key="d" value="The details of the new derived attribute"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="removeDerivedAttribute" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Remove a derived attribute from a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="spec" eType="#//DerivedAttributeSpec">
        <eAnnotations source="doc">
          <details key="d" value="The details of the derived attribute to be removed.&#xA;&#x9;&#x9;&#x9;Only the first three fields of the spec&#xA;&#x9;&#x9;&#x9;need to be populated"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listDerivedAttributes" upperBound="-1" eType="#//DerivedAttributeSpec"
        eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Lists the derived attributes of a Hawk instance. Only the first three fields of the spec are currently populated"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="addIndexedAttribute" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning #//InvalidIndexedAttributeSpec">
      <eAnnotations source="doc">
        <details key="d" value="Add a new indexed attribute to a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="spec" eType="#//IndexedAttributeSpec">
        <eAnnotations source="doc">
          <details key="d" value="The details of the new indexed attribute"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="removeIndexedAttribute" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Remove a indexed attribute from a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="spec" eType="#//IndexedAttributeSpec">
        <eAnnotations source="doc">
          <details key="d" value="The details of the indexed attribute to be removed"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="listIndexedAttributes" upperBound="-1" eType="#//IndexedAttributeSpec"
        eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Lists the indexed attributes of a Hawk instance"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getModel" upperBound="-1" eType="#//ModelElement" eExceptions="#//HawkInstanceNotFound #//HawkInstanceNotRunning">
      <eAnnotations source="doc">
        <details key="d" value="Returns the contents of one or more models indexed in a Hawk instance. Cross-model references are also resolved"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="repositoryUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the repository in which the model is contained"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="filePath" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The pattern(s) for the model file(s) in the repository"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeAttributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include attributes (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeReferences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include references (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeNodeIDs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include node IDs (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="false"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getRootElements" upperBound="-1" eType="#//ModelElement">
      <eAnnotations source="doc">
        <details key="d" value="Returns the root objects of one or more models indexed in a Hawk instance."/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The name of the Hawk instance"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="repositoryUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The URI of the repository in which the model is contained"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="filePath" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The pattern(s) for the model file(s) in the repository"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeAttributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include attributes (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="includeReferences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="doc">
          <details key="d" value="Whether to include references (true) or not (false)"/>
          <details key="optional" value="true"/>
          <details key="default" value="true"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelElementChangeType">
    <eAnnotations source="doc">
      <details key="d" value="Enumeration with the different types of changes that can happen to a model element."/>
    </eAnnotations>
    <eLiterals name="ADDED">
      <eAnnotations source="doc">
        <details key="d" value="The model element was added to the model"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REMOVED" value="1">
      <eAnnotations source="doc">
        <details key="d" value="The model element was removed from the model"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UPDATED" value="2">
      <eAnnotations source="doc">
        <details key="d" value="The contents of the model element were changed"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementChange">
    <eAnnotations source="doc">
      <details key="d" value="Entity that reflects a single change on a single model element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//ModelElement"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="The model element that was changed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ModelElementChangeType">
      <eAnnotations source="doc">
        <details key="d" value="The type of change performed on the model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="For changes of type UPDATED, the path within the element that was updated."/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HawkInstanceNotFound">
    <eAnnotations source="doc">
      <details key="d" value="No Hawk instance exists with that name."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HawkInstanceNotRunning">
    <eAnnotations source="doc">
      <details key="d" value="The selecte Hawk instance is not running."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidMetamodel">
    <eAnnotations source="doc">
      <details key="d" value="The provided metamodel is not valid (e.g. unparsable or inconsistent)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the metamodel not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownQueryLanguage">
    <eAnnotations source="doc">
      <details key="d" value="The specified query language is not supported by the operation."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownRepositoryType">
    <eAnnotations source="doc">
      <details key="d" value="The specified repository type is not supported by the operation."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidQuery">
    <eAnnotations source="doc">
      <details key="d" value="The specified query is not valid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the query not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidDerivedAttributeSpec">
    <eAnnotations source="doc">
      <details key="d" value="The derived attribute specification is not valid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the spec not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidIndexedAttributeSpec">
    <eAnnotations source="doc">
      <details key="d" value="The indexed attribute specification is not valid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the spec not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidPollingConfiguration">
    <eAnnotations source="doc">
      <details key="d" value="The polling configuration is not valid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the spec not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OfflineCollaboration">
    <eAnnotations source="doc">
      <details key="d" value="&#xA;The following service operations expose the capabilities of the offline collaboration framework&#xA;developed in Work Package 4. The framework is discussed in detail in D4.3.&#xA;"/>
    </eAnnotations>
    <eOperations name="checkout" upperBound="-1" eType="#//CollaborationResource"
        eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//CollaborationResourceNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Performs the checkout operation"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="resources" upperBound="-1" eType="#//CollaborationResourceReference">
        <eAnnotations source="doc">
          <details key="d" value="The references to the required resources"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="commit" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//CollaborationResourceNotFound #//CollaborationResourceLocked">
      <eAnnotations source="doc">
        <details key="d" value="Performs the commit operation"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="resources" upperBound="-1" eType="#//CollaborationResourceReference">
        <eAnnotations source="doc">
          <details key="d" value="The references to the required resources"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="pull" upperBound="-1" eType="#//CollaborationResource" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//CollaborationResourceNotFound #//MergeRequired">
      <eAnnotations source="doc">
        <details key="d" value="Performs the pull operation"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="resources" upperBound="-1" eType="#//CollaborationResourceReference">
        <eAnnotations source="doc">
          <details key="d" value="The references to the required resources"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="operationModel" eType="#//OperationModel">
        <eAnnotations source="doc">
          <details key="d" value="The operations executed on the client"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="publishLockDefinition" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//InvalidCollaborationLockQuerySpec">
      <eAnnotations source="doc">
        <details key="d" value="Publishes a lock definition"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="specification" eType="#//CollaborationLockQuerySpec">
        <eAnnotations source="doc">
          <details key="d" value="The lock query specification"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="unpublishLockDefinition" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//InvalidCollaborationLockQuerySpec #//CollaborationLockQueryNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Unpublish a lock definition"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="specification" eType="#//CollaborationLockQuerySpec">
        <eAnnotations source="doc">
          <details key="d" value="The lock query specification"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="lock" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//InvalidCollaborationLockQuerySpec #//CollaborationResourceLocked">
      <eAnnotations source="doc">
        <details key="d" value="Locks the pattern with the given bindings"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="specification" eType="#//CollaborationQueryInvocationSpecification">
        <eAnnotations source="doc">
          <details key="d" value="The lock specification with pattern and its bindings"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="unlock" eExceptions="#//VCSAuthenticationFailed #//VCSAuthorizationFailed #//InvalidCollaborationLockQuerySpec #//CollaborationLockQueryNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Unlocks the pattern with the given bindings"/>
      </eAnnotations>
      <eParameters name="credentials" eType="#//Credentials">
        <eAnnotations source="doc">
          <details key="d" value="The credentials of the user in the underlying VCS"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="specification" eType="#//CollaborationQueryInvocationSpecification">
        <eAnnotations source="doc">
          <details key="d" value="The lock specification with pattern and its bindings"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationLockQuerySpec">
    <eAnnotations source="doc">
      <details key="d" value="Specification of a lock on a set of model elements, without bindings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternFQN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Fully qualified name of the pre-existing query."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationQueryInvocationSpecification">
    <eAnnotations source="doc">
      <details key="d" value="Specification of a lock on a set of model elements, with bindings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternFQN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Fully qualified name of the pre-existing query."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//CollaborationQueryBinding" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Name/value bindings to be provided to the query."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationQueryBinding">
    <eAnnotations source="doc">
      <details key="d" value="Name/value binding used within a lock pattern"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Name of the query parameter being bound"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Value to be bound to the query parameter"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationResourceReference" abstract="true">
    <eAnnotations source="doc">
      <details key="d" value="Base entity for resource references in the collaboration API"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The URI of the repository containing the resource"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationGitResourceReference" eSuperTypes="#//CollaborationResourceReference">
    <eAnnotations source="doc">
      <details key="d" value="Reference to a resource in a Git repository"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the Git branch to which new commits should be pushed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The SHA1 identifier of the commit with the resource."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationSvnResourceReference" eSuperTypes="#//CollaborationResourceReference">
    <eAnnotations source="doc">
      <details key="d" value="Reference to a resource in a SVN repository"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The revision number containing the resource."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The path to the resource within the SVN repository."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationResource">
    <eAnnotations source="doc">
      <details key="d" value="Contents of a resource in the collaboration API"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="#//File">
      <eAnnotations source="doc">
        <details key="d" value="File with the contents of the resource"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credentials">
    <eAnnotations source="doc">
      <details key="d" value="Credentials of the client in the target VCS"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Username for logging into the VCS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Password for logging into the VCS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationModel">
    <eAnnotations source="doc">
      <details key="d" value="&#xA;Operational trace that encodes the operations carried out by the user locally over the models.&#xA;Its internal schema is presented in D4.3 and will be refined in D4.2.&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudATL">
    <eAnnotations source="doc">
      <details key="d" value="&#xA;The following service operations expose the capabilities of the cloud-enabled&#xA;version of the ATL transformation language which is currently under development and&#xA;will be presented in M24 in D3.3&#xA;"/>
    </eAnnotations>
    <eOperations name="launch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//InvalidTransformation #//InvalidModelSpec">
      <eAnnotations source="doc">
        <details key="d" value="Invokes a cloud-based transformation in a batch non-blocking mode.&#xA;&#x9;&#x9;&#x9;Returns a token that can be used to check the status of the transformation."/>
      </eAnnotations>
      <eParameters name="transformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="The ATL source-code of the transformation"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="source" upperBound="-1" eType="#//ModelSpec">
        <eAnnotations source="doc">
          <details key="d" value="The input models of the transformation"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="target" upperBound="-1" eType="#//ModelSpec">
        <eAnnotations source="doc">
          <details key="d" value="The target models of the transformation"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getJobs" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Lists the ids of the transformation jobs tracked by this server"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getStatus" eType="#//TransformationStatus" eExceptions="#//TransformationTokenNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Returns the status of a previously invoked transformation"/>
      </eAnnotations>
      <eParameters name="token" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="A valid token returned by a previous call to launch()"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="kill" eExceptions="#//TransformationTokenNotFound">
      <eAnnotations source="doc">
        <details key="d" value="Kills a previously invoked transformation"/>
      </eAnnotations>
      <eParameters name="token" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="doc">
          <details key="d" value="A valid token returned by a previous call to launch()"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eAnnotations source="doc">
      <details key="d" value="Represents a model element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Unique ID of the model element (not set if using position-based references)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="URI of the metamodel to which the type of the element belongs (not set if equal to that of the previous model element)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Name of the type that the model element is an instance of (not set if equal to that of the previous model element)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeSlot" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Slots holding the values of the model element's attributes, if any have been set"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//ReferenceSlot" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Slots holding the values of the model element's references, if any have been set"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//ContainerSlot" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Slots holding contained model elements, if any have been set"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eAnnotations source="doc">
      <details key="d" value="Represents a slot that can store the value(s) of a property of a model element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the model element property the value of which is stored in this slot"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSlot" eSuperTypes="#//Slot">
    <eAnnotations source="doc">
      <details key="d" value="Represents a slot that can store the value(s) of an attribute of a model element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Variant"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Variant value of the slot."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceSlot" eSuperTypes="#//Slot">
    <eAnnotations source="doc">
      <details key="d" value="&#xA;Represents a slot that can store the value(s) of a reference  of a model element.&#xA;References can be expressed as positions within a result tree (using pre-order traversal)&#xA;or IDs. id, ids, position, positions and mixed are all mutually exclusive. At least one position&#xA;or one ID must be given.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Position of the referenced element (if there is only one position-based reference in this slot)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Positions of the referenced elements (if more than one)."/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Unique identifier of the referenced element (if there is only one ID based reference in this slot)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Unique identifiers of the referenced elements (if more than one)."/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mixed" upperBound="-1"
        eType="#//MixedReference" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Mix of identifier- and position-bsaed references (if there is at least one position and one ID"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedReference">
    <eAnnotations source="thrift">
      <details key="union" value="true"/>
    </eAnnotations>
    <eAnnotations source="doc">
      <details key="d" value="Represents a reference to a model element: it can be an identifier or a position.&#xA;Only used when the same ReferenceSlot has both identifier-based and position-based references.&#xA;This may be the case if we are retrieving a subset of the model which has references&#xA;between its elements and with elements outside the subset at the same time."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Identifier-based reference to a model element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Position-based reference to a model element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerSlot" eSuperTypes="#//Slot">
    <eAnnotations source="doc">
      <details key="d" value="Represents a slot that can store other model elements within a model element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Contained elements for this slot."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarOrReference">
    <eAnnotations source="thrift">
      <details key="union" value="true"/>
    </eAnnotations>
    <eAnnotations source="doc">
      <details key="d" value="Union type for a scalar value or a reference to a model element. Useful for heterogeneous collections."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant">
    <eAnnotations source="thrift">
      <details key="union" value="true"/>
    </eAnnotations>
    <eAnnotations source="doc">
      <details key="d" value="Union type for a single scalar value or a homogeneous collection of scalar values."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vBytes" eType="#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vBooleans" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vShorts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vIntegers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vLongs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vDoubles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vStrings" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSpec">
    <eAnnotations source="doc">
      <details key="d" value="Captures information about source/target models of ATL transformations"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The local name of the model in the transformation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The URI from which the model will be loaded or to which it will be persisted"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelUris" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The URIs of the metamodels to which elements of the model conform"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexedAttributeSpec">
    <eAnnotations source="doc">
      <details key="d" value="Used to configure Hawk's indexed attributes (discussed in D5.3)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The URI of the metamodel to which the indexed attribute belongs"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the type to which the indexed attribute belongs"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the indexed attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedAttributeSpec">
    <eAnnotations source="doc">
      <details key="d" value="Used to configure Hawk's derived attributes (discussed in D5.3)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The URI of the metamodel to which the derived attribute belongs"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the type to which the derived attribute belongs"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the derived attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The (primitive) type of the derived attribute"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="The multiplicity of the derived attribute"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="A flag specifying whether the order of the values of the derived attribute is significant (only makes sense when isMany=true)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="A flag specifying whether the the values of the derived attribute are unique (only makes sense when isMany=true)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationLanguage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The language used to express the derivation logic"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationLogic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="An executable expression of the derivation logic in the language above"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationStatus">
    <eAnnotations source="doc">
      <details key="d" value="Used to report the status of a long-running transformation by CloudATL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="True if the transformation has finished, false otherwise"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elapsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="doc">
        <details key="d" value="Time passed since the start of execution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Description of the error that caused the transformation to fail"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HawkInstance">
    <eAnnotations source="doc">
      <details key="d" value="Status of a Hawk instance"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The name of the instance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="running" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="Whether the instance is running or not"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserProfile">
    <eAnnotations source="doc">
      <details key="d" value="Minimal details about registered users"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The real name of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="admin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="Whether the user has admin rights (i.e. so that they can create new users, change the status of admin users etc)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteArray" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eAnnotations source="doc">
      <details key="d" value="A file to be sent through the network"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" eType="#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationFailed">
    <eAnnotations source="doc">
      <details key="d" value="The client failed to prove its identity in MONDO or did not have the necessary permissions."/>
      <details key="exception" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserExists">
    <eAnnotations source="doc">
      <details key="d" value="The specified username already exists."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserNotFound">
    <eAnnotations source="doc">
      <details key="d" value="The specified username does not exist."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VCSAuthenticationFailed">
    <eAnnotations source="doc">
      <details key="d" value="The client failed to prove its identity in the VCS."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VCSAuthorizationFailed">
    <eAnnotations source="doc">
      <details key="d" value="The client does not have the required permissions in the VCS to perform the operation."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationResourceNotFound">
    <eAnnotations source="doc">
      <details key="d" value="The resource does not exist in the VCS."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceReference" eType="#//CollaborationResourceReference"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Reference to the missing resource."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationResourceLocked">
    <eAnnotations source="doc">
      <details key="d" value="The resource is currently locked for collaboration."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceReference" eType="#//CollaborationResourceReference"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="Reference to the locked resource."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeRequired">
    <eAnnotations source="doc">
      <details key="d" value="The operation requires a merge before it can be retried."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidCollaborationLockQuerySpec">
    <eAnnotations source="doc">
      <details key="d" value="The lock query specification is not valid."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationLockQueryNotFound">
    <eAnnotations source="doc">
      <details key="d" value="No matching lock exists."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidTransformation">
    <eAnnotations source="doc">
      <details key="d" value="The transformation is not valid: it is unparsable or inconsistent."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the transformation not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Location of the problem, if applicable. Usually a combination of line and column numbers."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidModelSpec">
    <eAnnotations source="doc">
      <details key="d" value="The model specification is not valid: the model or the metamodels are inaccessible or invalid."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spec" eType="#//ModelSpec"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="A copy of the invalid model specification."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Reason for the spec not being valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationTokenNotFound">
    <eAnnotations source="doc">
      <details key="d" value="The specified transformation token does not exist within the invokved MONDO instance."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="Transformation token which was not found within the invoked MONDO instance."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
